name: nightly

on:
  schedule:
  - cron: "0 0 * * *"
  # Manual dispatch, only for testing purposes
  # See https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: "${{secrets.COMMIT_KEY}}"

      # Setup Node.js
      - name: Node.js
        uses: actions/setup-node@v3

      # Install dependencies
      - run: npm ci --verbose

      # Config git user name and email
      - name: Config git user name and email
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      # Update tests
      - name: Update tests
        id: update
        run: echo "new_version=`scripts/update.js`" >> "$GITHUB_OUTPUT"

      - name: Update dependencies
        if : ${{ steps.update.outputs.new_version != '' }}
        run: |
          npx npm-check-updates -u
          npm install --verbose

      # Ensure extracted tests are working
      - name: Run tests
        if : ${{ steps.update.outputs.new_version != '' }}
        run: npm test

      # Commit and push changes
      - name: Commit and push changes
        if : ${{ steps.update.outputs.new_version != '' }}
        run: npm run release

      # Create release
      - name: Create release
        if : ${{ steps.update.outputs.new_version != '' }}
        run: |
          gh release create \
            v${{ steps.update.outputs.new_version }} \
            --generate-notes \
            --verify-tag
        env:
          GH_TOKEN: ${{ github.token }}
